# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num', models.IntegerField(default=0)),
                ('LED_COUNT', models.IntegerField(default=16)),
                ('LED_PIN', models.IntegerField(default=18)),
                ('LED_BRIGHTNESS', models.IntegerField(default=50)),
                ('LED_STRIP', models.CharField(default='ws.WS2811_STRIP_GRB', max_length=200)),
            ],
        ),
    ]
