# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 19:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strip',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='000000', max_length=10), size=8), blank=True, null=True, size=8),
        ),
    ]
