# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20170608_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='strip',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
